### ISSUE TITLE
Scenario type

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/loco-core#10]
## Description
This keeps track of the implementation of the `scenario_t` type, which serves as a container for all elements that can be simulated, i.e. single bodies and articulated systems.

The API should look something like this:
```c++
// Should we use the heap?
auto scenario = std::make_unique<::loco::Scenario>();

constexpr Scalar radius = 1.0;
const Vec3 pos(1.0, 1.0, 1.0);
const Quat rot(1.0, 0.0, 0.0, 0.0);
auto sphere = std::make_unique<::loco::Sphere>(radius, pos, rot);

scenario->AddBody(sphere);

// Or maybe not
::loco::Scenario scenario;

constexpr Scalar radius = 1.0;
const Vec3 pos(1.0, 1.0, 1.0);
const Quat rot(1.0, 0.0, 0.0, 0.0);
::loco::Sphere sphere(radius, pos, rot);

scenario.AddBody(sphere)
```

```python
scenario = loco.Scenario()

radius = 1.0
pos = np.array([1.0, 1.0, 1.0], dtype=np.float32)
rot = np.array([1.0, 0.0, 0.0, 0.0], dtype=np.float32)
sphere = loco.Sphere(radius, pos, rot)

scenario.AddBody(sphere)
```

## Tasks
- [ ] Example of usage (C++)
- [ ] Python bindings
- [ ] Example of usage (Python)
- [ ] Documentation (API auto-generated by Sphinx + Breathe)
- [ ] Documentation (custom .rst for detailed info)
