### ISSUE TITLE
Core structures

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/loco-core#9]
## Description
This item keeps track of the remaining features related to the core structures we'll use to build a simulation.

## Tasks
- [ ] Examples of usage (C++)
- [ ] Update Python bindings using as reference the implementation of mjModel bindings from [MuJoCo][0]
- [ ] Examples of usage (Python)
- [ ] API docs (auto-generated by Sphinx and Breathe)
- [ ] Detailed docs (.rst custom made)

[0]: <https://github.com/deepmind/mujoco/blob/8efb04eb793bd255a4da4d9a2a3888bdde0ef004/python/mujoco/structs.h#L72> (ref-mujoco-bindings-1)
